<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="8" failed="1" total="9" passed="0">
  <reporter-output>
    <line>
      <![CDATA[[2016-06-21 13:37:35]java.io.IOException: Cannot run program "/Users/qa/android-sdks/platform-tools/adb": error=2, No such file or directory]]>
    </line>
    <line>
      <![CDATA[<span style="color:#FF7F27"><b>[2016-06-21 13:37:35]  java.lang.NullPointerException</b></span><br />]]>
    </line>
    <line>
      <![CDATA[[2016-06-21 13:37:35]=========================Login=============================]]>
    </line>
    <line>
      <![CDATA[<span style="color:#FF7F27"><b>[2016-06-21 13:37:35]  [Faile] Quit the app.</b></span><br />]]>
    </line>
    <line>
      <![CDATA[<span style="color:#FF7F27"><b>[2016-06-21 13:37:35]  java.lang.NullPointerException</b></span><br />]]>
    </line>
  </reporter-output>
  <suite name="All" duration-ms="556" started-at="2016-06-21T05:37:35Z" finished-at="2016-06-21T05:37:35Z">
    <groups>
    </groups>
    <test name="All test" duration-ms="556" started-at="2016-06-21T05:37:35Z" finished-at="2016-06-21T05:37:35Z">
      <class name="com.appium.Android_testcase.Demo">
        <test-method status="PASS" signature="beforeTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.appium.Android_testcase.Demo@1cf0b007]" name="beforeTest" is-config="true" duration-ms="281" started-at="2016-06-21T13:37:35Z" finished-at="2016-06-21T13:37:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[86341949@qq.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[dieson]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Australia]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[0JVV-Legal commentry of NSW UO]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[[2016-06-21 13:37:35]java.io.IOException: Cannot run program "/Users/qa/android-sdks/platform-tools/adb": error=2, No such file or directory]]>
            </line>
            <line>
              <![CDATA[<span style="color:#FF7F27"><b>[2016-06-21 13:37:35]  java.lang.NullPointerException</b></span><br />]]>
            </line>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="login(java.util.Map)[pri:0, instance:com.appium.Android_testcase.Demo@1cf0b007]" name="login" duration-ms="2" started-at="2016-06-21T13:37:35Z" data-provider="dp" finished-at="2016-06-21T13:37:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{PageNO=9, phone=1800 999 906, resetMsgExpect=Your password reset request has been sent., TitleName=Cross on Evidence, emailExpect=techsupport@lexisnexis.com.au, history_TOC=Update, open_TOC=Supreme Court Rules 1970 (NSW) compared to Uniform Civil Procedure Rules 2005 (NSW), contactIconExpect=Contact us, password=, result_TOC=Section 43 â€” Propensity evidence offered by prosecution about defendants, result_guide_card=...test employed by s 43 is not appreciably different from the general test..., HistoryName=Cross on Evidence, username=dieson@163.com, PageNOVerify=9, contactIcon=Contact us, history_name=02I6-02I6Cross On Evidence (NZ), msgActual=Please enter both your email and password to log in., TocName=An obscure maxim, search_text=Test, resetMsg=Your password reset request has been sent., TitleNamePop=Cross on Evidence, TOCNamePop=An obscure maxim, resetusername=dontmove@lexisred.com, HistoryToc=An obscure maxim, changeMsg=Your password has been successfully changed., changepassword=dieson, post=Level 9
Locked Bag 2222 Chatswood Delivery Centre
Chatswood NSW 2067, fax=02 9422 2405, faxExpect=02 9422 2405, TOC=Exclusive possession the touchstone of a lease, postDx=Street Address: LexisNexis
DX 29590 Chatswood
Tower 2, 475-495 Victoria Avenue
Chatswood NSW 2067, resetpassword=O6GJBTqB, postDxExpect=Street Address: LexisNexis
DX 29590 Chatswood
Tower 2, 475-495 Victoria Avenue
Chatswood NSW 2067, postExpect=Level 9
Locked Bag 2222 Chatswood Delivery Centre
Chatswood NSW 2067, phoneExpect=1800 999 906, msgExpect=Please enter both your email and password to log in., country=Australia, email=techsupport@lexisnexis.com.au, changeMsgExpect=Your password has been successfully changed., TOCVerify=Exclusive possession the touchstone of a lease, result_publication=Document, resetcountry=Australia}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.appium.driver.ElementUtils.isExistElement(ElementUtils.java:113)
	at com.appium.Android_page.LoginPage.skipTour(LoginPage.java:76)
	at com.appium.Android_testcase.Demo.login(Demo.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:73)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:94)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[[2016-06-21 13:37:35]=========================Login=============================]]>
            </line>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="SKIP" signature="download()[pri:0, instance:com.appium.Android_testcase.Demo@1cf0b007]" name="download" duration-ms="0" started-at="2016-06-21T13:37:35Z" depends-on-methods="com.appium.Android_testcase.Demo.login" finished-at="2016-06-21T13:37:35Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Demo.download()[pri:0, instance:com.appium.Android_testcase.Demo@1cf0b007] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Demo.download()[pri:0, instance:com.appium.Android_testcase.Demo@1cf0b007] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:73)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:94)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- download -->
        <test-method status="SKIP" signature="contact(java.util.Map)[pri:0, instance:com.appium.Android_testcase.Demo@1cf0b007]" name="contact" duration-ms="0" started-at="2016-06-21T13:37:35Z" data-provider="dp" depends-on-methods="com.appium.Android_testcase.Demo.download" finished-at="2016-06-21T13:37:35Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Demo.contact(java.util.Map)[pri:0, instance:com.appium.Android_testcase.Demo@1cf0b007] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Demo.contact(java.util.Map)[pri:0, instance:com.appium.Android_testcase.Demo@1cf0b007] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:73)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:94)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contact -->
        <test-method status="SKIP" signature="filterPublication()[pri:0, instance:com.appium.Android_testcase.Demo@1cf0b007]" name="filterPublication" duration-ms="0" started-at="2016-06-21T13:37:35Z" depends-on-methods="com.appium.Android_testcase.Demo.contact" finished-at="2016-06-21T13:37:35Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Demo.filterPublication()[pri:0, instance:com.appium.Android_testcase.Demo@1cf0b007] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Demo.filterPublication()[pri:0, instance:com.appium.Android_testcase.Demo@1cf0b007] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:73)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:94)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- filterPublication -->
        <test-method status="SKIP" signature="index()[pri:0, instance:com.appium.Android_testcase.Demo@1cf0b007]" name="index" duration-ms="0" started-at="2016-06-21T13:37:35Z" depends-on-methods="com.appium.Android_testcase.Demo.filterPublication" finished-at="2016-06-21T13:37:35Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Demo.index()[pri:0, instance:com.appium.Android_testcase.Demo@1cf0b007] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Demo.index()[pri:0, instance:com.appium.Android_testcase.Demo@1cf0b007] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:73)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:94)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- index -->
        <test-method status="SKIP" signature="recentHistory(java.util.Map)[pri:0, instance:com.appium.Android_testcase.Demo@1cf0b007]" name="recentHistory" duration-ms="0" started-at="2016-06-21T13:37:35Z" data-provider="dp" depends-on-methods="com.appium.Android_testcase.Demo.index" finished-at="2016-06-21T13:37:35Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Demo.recentHistory(java.util.Map)[pri:0, instance:com.appium.Android_testcase.Demo@1cf0b007] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Demo.recentHistory(java.util.Map)[pri:0, instance:com.appium.Android_testcase.Demo@1cf0b007] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:73)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:94)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- recentHistory -->
        <test-method status="SKIP" signature="search(java.util.Map)[pri:0, instance:com.appium.Android_testcase.Demo@1cf0b007]" name="search" duration-ms="0" started-at="2016-06-21T13:37:35Z" data-provider="dp" depends-on-methods="com.appium.Android_testcase.Demo.TOCHide" finished-at="2016-06-21T13:37:35Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Demo.search(java.util.Map)[pri:0, instance:com.appium.Android_testcase.Demo@1cf0b007] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Demo.search(java.util.Map)[pri:0, instance:com.appium.Android_testcase.Demo@1cf0b007] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:73)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:94)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- search -->
        <test-method status="SKIP" signature="TOCHide()[pri:0, instance:com.appium.Android_testcase.Demo@1cf0b007]" name="TOCHide" duration-ms="0" started-at="2016-06-21T13:37:35Z" depends-on-methods="com.appium.Android_testcase.Demo.recentHistory" finished-at="2016-06-21T13:37:35Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Demo.TOCHide()[pri:0, instance:com.appium.Android_testcase.Demo@1cf0b007] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Demo.TOCHide()[pri:0, instance:com.appium.Android_testcase.Demo@1cf0b007] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:73)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:94)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TOCHide -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.appium.Android_testcase.Demo@1cf0b007]" name="afterTest" is-config="true" duration-ms="0" started-at="2016-06-21T13:37:35Z" finished-at="2016-06-21T13:37:35Z">
          <reporter-output>
            <line>
              <![CDATA[<span style="color:#FF7F27"><b>[2016-06-21 13:37:35]  [Faile] Quit the app.</b></span><br />]]>
            </line>
            <line>
              <![CDATA[<span style="color:#FF7F27"><b>[2016-06-21 13:37:35]  java.lang.NullPointerException</b></span><br />]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="SKIP" signature="logout()[pri:0, instance:com.appium.Android_testcase.Demo@1cf0b007]" name="logout" duration-ms="0" started-at="2016-06-21T13:37:35Z" depends-on-methods="com.appium.Android_testcase.Demo.search" finished-at="2016-06-21T13:37:35Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Demo.logout()[pri:0, instance:com.appium.Android_testcase.Demo@1cf0b007] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Demo.logout()[pri:0, instance:com.appium.Android_testcase.Demo@1cf0b007] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:73)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:94)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
      </class> <!-- com.appium.Android_testcase.Demo -->
    </test> <!-- All test -->
  </suite> <!-- All -->
</testng-results>
